apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: jeanpaulxiao2/app4_client
          ports:
              - containerPort: 3000
